config/routes.rb
Rails.application.routes.draw do
  get 'hello_world/index'
  get 'home/index'
  resources :room_messages
  resources :rooms
  devise_for :users
  resources :home, only: [:index, :new, :create]
  match '/contacts',  to: 'contacts#new', via:'get'
resources "contacts", only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root controller: :rooms, action: :index

  resources :room_messages
  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message

def headers
	{
:subject =>  "Small Talk contact",
:to => "heisler.lemos@gmail.com",
:from => %("#{name}" <#{email}>)
}
end
end

app/models/room.rb
class Room < ApplicationRecord

has_many :room_messages, dependent: :destroy,
			 inverse_of: :room
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :room
  belongs_to :user
  belongs_to :room, inverse_of: :room_messages

  def as_json(options)
  	super(options).merge(user_avatar_url: user.gravatar_url)
   end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   validates :username,  uniqueness: true, presence: true

def gravatar_url
  gravatar_id = Digest::MD5::hexdigest(email).downcase
  "https://gravatar.com/avatar/#{gravatar_id}.png"
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!
before_action :configure_permitted_parameters, if: :devise_controller?
protected

def configure_permitted_parameters
devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username])
end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

 def new
 	@contact = Contact.new
 end

 def create
    @contact = Contact.new(params[:contact])
 	@contact.request = request
 	if @contact.deliver
 		redirect_to  root_path, success: "Obrigado por enviar a mensagem. Entraremos em contacto consigo em breve"
 		puts "it sended"
 	else
 		render :new, danger: "Não foi possivel enviar a mensagem."
 		puts "it did not sended"
 	end
 end
end

app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
  end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
	before_action :load_entities


	def create
		@room_message = RoomMessage.create user: current_user,
												 room: @room,
												 message: params.dig(:room_message, :message)

	RoomChannel.broadcast_to @room, @room_message

	end

	protected 

	def load_entities
		@room = Room.find params.dig(:room_message, :room_id)
	end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

before_action :load_entities

def index
	@rooms = Room.all
end


def show
@room_message = RoomMessage.new room: @room
@room_messages = @room.room_messages.includes(:user)
end

def new
	@room = Room.new 
end

def create
	@room = Room.new permitted_parameters

	if @room.save
		flash[:success] = "Room #{@room.name} was created sucessfully"
		redirect_to rooms_path
	else
		render :new
	end
end

def edit
end

def update
	if @room.update_attibutes(permitted_parameters)
		flash[:sucess] = "Room #{@room.name} was updated sucessfully"
		redirect_to rooms_path
	else
		render :new
	end
end

def load_entities
	@rooms = Room.all
	@room = Room.find(params[:id]) if params[:id]

end

def permitted_parameters
	params.require(:room).permit(:name)
end

end

app/helpers/application_helper.rb
module ApplicationHelper

#def gravatar_url(user)
#gravatar_id = Digest::MD5::hexdigest(user.email).downcase
#url = "https://gravatar.com/avatar/#{gravatar_id}.png"
#end

end

app/helpers/hello_world_helper.rb
module HelloWorldHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/contacts/create.html.erb
<%= stylesheet_link_tag    'contacts', media: 'all', 'data-turbolinks-track': 'reload' %>
<div>

</div>

app/views/contacts/new.html.erb
<%= stylesheet_link_tag    'contacts', media: 'all', 'data-turbolinks-track': 'reload' %>


<div align="center">
<div style=" width: 900px;  height: 900px; " align="center">
<br>
<h1 style="color: white; font-family: 'Roboto', sans-serif; font-size: 60px;" class="text-success"> Envie-nos um email ! </h1>
<%= simple_form_for @contact, :html => {:class => 'form-vertical'} do |f| %>
<br>
<%= f.input :name, :require => true, :required => true, :input_html => {:style=> 'width: 100%; color: black; text-align: center;'} %>
<br>
<%= f.input :email, :require => true, :required => true, :input_html => { :style=> 'width: 100%; color: black; text-align: center;'} %>
<br>
<br>
<br>
<%= f.input :message, :as => :text, :required => true, :input_html => {:rows => 9, :style => 'width: 900px; text-align: center;'} %>
<div>
</br>
<%= f.button :submit, 	"Enviar" %>
</div>
<% end %>
</div>
</div>

app/views/hello_world/index.html.erb
<center><h1>Hello, world!</h1></center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmallTalks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <style>
/* FOOTER */

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
  margin-top: 6px;
  margin-bottom: 16px;
  resize: vertical;
}

input[type=submit] {
  background-color: #4CAF50;
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 2px;
  background-color: #f2f2f2;
  padding: 20px;
}


html, body {
  height: 100%;
  padding: 0px;
  margin: 0px;
}

.footer {
  background-color: #262130;
  color: white;
  height: 400px;
  position: relative;

}

.footer .footer-content {
  height: 350px;

}
table {
  position: absolute;
  top: 30%;
}

tr {
  text-align: center;
  font-size: 20px;

}

.page-wrapper {
  min-height: 40%;
}

.page-wrapper a:houver {
  color: lightblue;
}


.footer .footer-bottom {
  background: #231C2F;
  color: white;
  height: 50px;
  width: 100%;
  text-align: center;
  position: absolute;
  bottom: 0px;
  left: 0px;
  padding-top: 20px;
}

  </style>

  <body>

 <!-- <div class="container"> -->
  <div class="row">
  <div class="col-12">
   <%= render partial: 'shared/navigation_bar'%>
    <div class="my-3">

   <%= yield %>


    </div>
  </div>
   <!--</div>-->
</div>
  </body>

  <!-- Page Wrapper -->
<div class="page-wrapper">
</div>

  <br>
    <br>
  <br>


  <!-- // Page Wrapper -->

  <!-- footer -->

  <div class="footer">


    <div class="footer-content">
        <table style="width:100%">
  <tr>
    <th>Email Signup</th>
    <th>Contact</th> <!-- Needs a button to contact page -->
    <th>Terms of Use</th>   
    <th>Legal</th>  
  </tr>
  <tr>
    <td>Association Memberships</td>
    <td>Directions</td>
    <td>Phone</td>
    <td>Sitemap</td>
  </tr>
  <tr>
    <td>Job Hire</td>
    <td>Donate</td>
    <td>Social Icons Facebook Watsup Tumblr</td>
    <td>Privacy Policy</td>
  </tr>
</table>
      <div class="footer-section about" style="border-top: 5px solid  red;">
      </div>
       <div class="footer-section links"></div>
        <div class="footer-section contact-form">

        </div>
    </div>
    <div class="footer-bottom">
    &copy; small_talk  | Designed by Heisler

    </div >

  </div>
  <!-- //footer -->
</html>

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>
	<%= form.input :name %>
	<%= form.submit "Save", class: 'btn btn-success' %>
<% end %>	

app/views/rooms/_rooms.html.erb
<div class="mb-3">
<%= link_to new_room_path, class: 'btn btn-info'  do %>
	Create a room
<% end %>
</div>

<% if @rooms.present? %>
	<nav class="nav flex-column">
		<% @rooms.each do |room| %>
			<%= link_to room.name, room_path(room), class: 'nav-link room-nav-link' %>
		<% end %>
	</nav>
	<% else %>
		<div class="text-muted">
			The are no rooms
		</div>
	<% end %>

app/views/rooms/edit.html.erb
<h1>
	Editing room <%= @room.name %>
</h1>


<%= render partial: 'form' %>

app/views/rooms/index.html.erb
         <div class="row">
            <div class="col-12 col-md-3">
                   <%= render partial: 'rooms' %>

         </div>   



 		<div class="col">
 			<div class="alert alert-info">
 				<h4 class="alert-heading">
 					Welcome to  Small_Talk_!
 				</h4>

 				<p>
 					Created by Heisler Lemos
 				</p>

 				<hr />

 				<p>
               You can create your private channel with your team


 				</p>
 			</div>
 		</div>
</div>

app/views/rooms/new.html.erb
<h1>
Creating a chanell
</h1>


<%= render partial: 'form' %>

app/views/rooms/show.html.erb
<h1>
<%= @room.name%>
</h1>


<div class="row">
<div class="col-12 col-md-3">
	<%= render partial: 'rooms' %>
</div>


<div class="col">
<div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
		<% @room_messages.each do |room_message| %>
			<div class="chat-message-container">
			<div class="row no-gutters">
			<div class="col-auto text-center">
				<img src="<%= room_message.user.gravatar_url %>" class="avatar" alt="">
			</div>


			<div class="col">
				<div class="message-content">
					<p class="mb-1">
			<%= room_message.message %>
					</p>

			<div class="text-right">
			<small>

				<%= room_message.created_at %>
			</small>
		</div>
		</div>
		</div>
		</div>
		</div>
		<% end %>
	</div>


<%= simple_form_for @room_message, remote: true do |form| %>
	<div class="input-group mb-3">
		<%= form.input :message, as: :string,
								 wrapper: false,
								 label: false,
								 input_html: {
								 class: 'chat-input'
								 } %>
	<div class="input-group-append">
	<%= form.submit "Send", class: "btn btn-primary chat-input" %>
</div>
	</div>
		<%= form.input :room_id, as: :hidden %>
		<% end %>
	</div>
</div>



<div class="d-none" data-role="message-template">
  <div class="chat-message-container">
    <div class="row no-gutters">
      <div class="col-auto text-center">
        <img src="" class="avatar" alt="" data-role="user-avatar">
      </div>

      <div class="col">
        <div class="message-content">
          <p class="mb-1" data-role="message-text"></p>

          <div class="text-right">
            <small data-role="message-date"></small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark justify-content-between">

<a class="navbar-brand" href="#" style="color: white">Small_Talks_!</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-bar-collapse" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>


<% if current_user %>
<div class="dropdown">
 <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
<img class="avatar" src="<%= current_user.gravatar_url %>">

<%= current_user.username %>
 </a>


<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
<%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
</div>
</div>

<% end %>
</nav>